kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "mailu.fullname" . }}-nginx-overrides
{{- with .Values.front.overrides }}
data:
{{- .|toYaml|nindent 2}}
{{- end }}

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "mailu.fullname" . }}-postfix-overrides
{{- with .Values.postfix.overrides }}
data:
{{- .|toYaml|nindent 2}}
{{- end }}

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "mailu.fullname" . }}-dovecot-overrides
{{- with .Values.dovecot.overrides }}
data:
{{- .|toYaml|nindent 2}}
{{- end }}

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "mailu.fullname" . }}-rspamd-overrides
{{- with .Values.rspamd.overrides }}
data:
{{- .|toYaml|nindent 2}}
{{- end }}
